### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by hammadsaedi** [khattakdev/capture#11]
add functionality: copy to clipboard taken snapshot

**Comment by Manas-Kenge** [comment]
Can you assign this issue to me?

**Comment by hammadsaedi** [comment]
@princemishra01 does the image copy to the clipboard? Not working at my end.

cc: @khattakdev

**Comment by khattakdev** [comment]
@hammadsaedi What machine do you have and how did you try/test it?

**Comment by princemishra01** [comment]
> @princemishra01 does the image copy to the clipboard? Not working at my end.
> 
> cc: @khattakdev

yes it was working i tested it.
