### ISSUE TITLE
extensions conflict with `solidity`

### ISSUE THREAD

**Issue by hammadsaedi** [khattakdev/capture#16]
![image](https://github.com/khattakdev/capture/assets/71373419/f63e4d3b-a2c0-46fb-ac2b-da9378ee1b16)

**Comment by coding-cosmos** [comment]
@khattakdev how to reproduce this ? I have downloaded the solidity extension but I didn't get this error.

**Comment by khattakdev** [comment]
@hammadsaedi do you have steps to reproduce this?

Also - try reinstalling Solidity extension and see if that fixes it.

**Comment by hammadsaedi** [comment]
fix.

I just reinstalled.
