### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/capture#4]
`capture` is using [shiki](https://www.npmjs.com/package/shiki) for syntax highlighting. The default theme is `one-dark-pro` but there should be a way for the user to change the theme.

The best way is to have these settings in the vscode JSON.

**Comment by HamzaMateen** [comment]
Okay, I would love to work on such thing, but I am not very familiar with VSCode side of things, could you please guide me a bit further? Thanks

**Comment by khattakdev** [comment]
You would need to define configurations in `package.json` - which will be used as default values:

```
"contributes": {
    "configuration": {
        "title": "Capture settings",
        "properties": {
            "capture.themeName": {
                "type": "string",
                "default": "one-dark-pro",
                "description": "The theme to use."
            }
        }
    }
}
```

Next is to get the value when taking screenshot.

```
const configuration = vscode.workspace.getConfiguration('capture');
const themeName = configuration.get('themeName', 'one-dark-pro');  // The default value is 'one-dark-pro'
}
```

The `themeName` should be used for `shiki`.
```
const highlighter = await shiki.getHighlighter({
    theme: "one-dark-pro", // Here
  });
```

**Comment by HamzaMateen** [comment]
Thank you for the clarification, I will try my best!

**Comment by coding-cosmos** [comment]
@khattakdev I would like to work on this issue if @HamzaMateen is not working I have some progress on the issue

**Comment by HamzaMateen** [comment]
I tried my best to contribute, I get the idea as well, but I am facing issues related to setting up my environment. You may carry on from here. @khattakdev please un assign me. Thanks
