### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/capture#6]
Currently, the HTML files/content are not supportable because the puppeteer uses an HTML script to generate a screenshot.

**Comment by hammadsaedi** [comment]
@khattakdev can you assign this issue to me? Ig, I can figure it out. 🙂👍

**Comment by khattakdev** [comment]
Good luck.

**Comment by coding-cosmos** [comment]
@khattakdev I have added support for HTML . You can check it here [https://drive.google.com/file/d/1qrv3-STIF_14hSlZDU9nWKyxLG2ylo3d/view?usp=drive_link](url) . 
Should I raise a PR?

**Comment by hammadsaedi** [comment]
@khattakdev idk man, I took SS. It's working for me. 

PS: I did not change anything, 

![image](https://github.com/khattakdev/capture/assets/71373419/66fc5b9e-fa1e-458f-9f26-a297807f8268)

**Comment by coding-cosmos** [comment]
yeah now it's working... don't know how... when I tried it, it was giving an error.

**Comment by coding-cosmos** [comment]
@hammadsaedi Any idea how it's working ? I am really confused now!!

**Comment by khattakdev** [comment]
@hammadsaedi did you try taking a screenshot of something like the following:

```
<div class="header">
   <h1>home</h1>
</div>
```

**Comment by hammadsaedi** [comment]
@khattakdev working. xD
![image](https://github.com/khattakdev/capture/assets/71373419/5c372e0f-9ae8-4bb9-8049-64073bdbb8a3)

**Comment by khattakdev** [comment]
Ah I think this is working after I used `shiki`.
Let's move to next issue.
