### ISSUE TITLE
Clean the project

### ISSUE THREAD

**Issue by khattakdev** [khattakdev/capture#7]
There are some extra files in the repository that shouldn't be there, such as `vsc-extension-quickstart.md` `CascadiaCodePL.ttf` etc.

Clean up the repository by removing unnecessary files.

**Comment by himanshubalani** [comment]
I can work on this! Can you assign me the issue?

**Comment by himanshubalani** [comment]
I can work on this! Can you assign me the issue?

**Comment by lakshaysharma399** [comment]
I can work on this! Can you Assign it to me??

**Comment by ibrahimrehman1** [comment]
I would like to contribute to this one. Can you assign this to me?

**Comment by kelvinparmar** [comment]
I would like to contribute to this one. Can you assign this to me?

**Comment by Manas-Kenge** [comment]
Can you please assign this issue to me?

**Comment by khattakdev** [comment]
Since @himanshubalani was the first on this issue - I will hand it over to him.

Rest of can - feel free to claim any other available issue or create an issue that you think we should have.
Additionally - you can try this [npm package](https://github.com/khattakdev/minimalcommit)
